@API_URL = http://localhost:4000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkOTcxNjcwNzgsImV4cCI6MTY5NzE2NzEzOH0.8VLttwEtlFddLKArRoXlDcY8x4EybwnEfChTWx-3QW8

POST {{API_URL}}/cart/addToCart
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userID": "650ea44d5cc1a9050f51fe66",
    // "itemID": "6522981c8294ac72386e07b7"
    "itemID": "652386bbf1c0c2f53bbb7fa6"
    // "itemID": "65122b230655fca8f4852110"
}

###

POST {{API_URL}}/cart/getCartItems
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userID": "650ea44d5cc1a9050f51fe66"
}

###
POST {{API_URL}}/accounts/login
Content-Type: application/json

{
    "email":"nishantapaudel9@gmail.com",
    "password":"hello"
}

###